services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    container_name: mariadb
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=rootpassword
    ports:
      - '3306:3306'
    networks:
      - wp_network
  wordpress:
    image: docker.io/bitnami/wordpress:6
    container_name: wordpress
    restart: always
    ports:
       # TODO Expose http and https
#      - 8443:443
      - '8080:8080'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - DOMAINNAME=localhost
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=password
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
    networks:
      - wp_network
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  wp_network:
    name: wp_network  # Forces Docker to use this exact name
    driver: bridge