services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    container_name: mariadb
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=rootpassword
    ports:
      - '3306:3306'
    networks:
      - wp_network
  wordpress:
    image: docker.io/bitnami/wordpress:6
    container_name: wordpress
    restart: always
    ports:
       # TODO Expose http and https
#      - 8443:443
      - '8080:8080'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - DOMAINNAME=localhost
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=password
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_USERNAME=user # debug: these are defaults
      - WORDPRESS_PASSWORD=bitnami # debug
      - WORDPRESS_EMAIL=2yv3R@example.com
      - WORDPRESS_FIRST_NAME=Wordpress
      - WORDPRESS_LAST_NAME=Admin
    networks:
      - wp_network

#  wordpress-cli:
#      depends_on:
#          - mariadb
#          - wordpress
#      image: 'wordpress:cli'
#      entrypoint: wp
#      user: xfs
#      command: "/bin/sh -c ' sleep 10;  wp core install --url=\"http://localhost:8000\" --title=\"Sample Title\" --admin_name=admin --admin_password=admin --admin_email=you@domain.com '\n"
#      volumes:
#          - './wordpress:/var/www/html'
#          - './docker/wordpress/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro'
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  wp_network:
    name: wp_network  # Forces Docker to use this exact name
    driver: bridge
